import{useMemo,useState}from'react';import{supabase}from'../lib/supabase';
const fmtDate=v=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'full'}).format(new Date(v));
const fmtTime=v=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v));
const label={pending:'Pendente',confirmed:'Confirmado',completed:'Concluído',cancelled:'Cancelado',no_show:'Não compareceu'};
export default function MyAppointments(){const[name,setName]=useState('');const[phone,setPhone]=useState('');const[logged,setLogged]=useState(false);const[items,setItems]=useState([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[cancelId,setCancelId]=useState('');const[reason,setReason]=useState('');
async function loadMine(){setBusy(true);setError('');try{const{data,error}=await supabase.rpc('client_appointments',{p_name:name.trim(),p_phone:phone});if(error)throw error;setItems(data||[]);setLogged(true)}catch(e){setError(e.message||'Não foi possível localizar seus horários.')}finally{setBusy(false)}}
async function login(e){e.preventDefault();if(!name.trim()||!phone.trim())return setError('Informe seu nome e WhatsApp.');await loadMine()}
async function cancel(){if(!cancelId)return;const ok=window.confirm('Tem certeza que deseja cancelar este horário? Ao confirmar, ele será liberado para outra cliente.');if(!ok)return;setBusy(true);setError('');try{const{data,error}=await supabase.rpc('client_cancel_appointment',{p_id:cancelId,p_name:name.trim(),p_phone:phone,p_reason:reason});if(error)throw error;if(!data)throw new Error('Não foi possível cancelar este horário. Ele pode já estar concluído, cancelado ou não pertencer a este acesso.');setCancelId('');setReason('');await loadMine()}catch(e){setError(e.message||'Não foi possível cancelar o agendamento.')}finally{setBusy(false)}}
const upcoming=useMemo(()=>items.filter(x=>new Date(x.start_datetime)>new Date()&&x.status!=='cancelled'),[items]);const history=useMemo(()=>items.filter(x=>!upcoming.some(u=>u.id===x.id)),[items]);
if(!logged)return <section className="section page narrow"><span className="eyebrow">ÁREA DA CLIENTE</span><h1>Meus horários</h1><form className="booking" onSubmit={login}><p className="hint">Entre com o mesmo nome e WhatsApp usados no agendamento. Se o Studio cadastrou seu horário pelo painel, use os dados informados à profissional.</p><label>Seu nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Digite seu nome"/></label><label>Seu WhatsApp<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Ex.: 51999999999" inputMode="tel"/></label>{error&&<div className="panel"><b>{error}</b></div>}<button className="btn full" disabled={busy}>{busy?'Buscando...':'Acessar meus horários'}</button></form></section>;
const card=x=><article className="client-appointment" key={x.id}><div><span className="eyebrow">{label[x.status]||x.status}</span><h3>{x.service_name}</h3><p><b>{fmtDate(x.start_datetime)}</b></p><p>{fmtTime(x.start_datetime)} até {fmtTime(x.end_datetime)}</p><p>Profissional: <b>{x.professional_name}</b></p>{x.notes&&<p>Observações: {x.notes}</p>}{x.cancellation_reason&&<p>Motivo do cancelamento: {x.cancellation_reason}</p>}</div>{new Date(x.start_datetime)>new Date()&&x.status!=='cancelled'&&x.status!=='completed'&&<button className="btn ghost" onClick={()=>{setCancelId(x.id);setReason('')}}>Cancelar horário</button>}</article>;
return <section className="section page"><div className="client-portal-head"><div><span className="eyebrow">ÁREA DA CLIENTE</span><h1>Olá, {name}</h1><p>Confira seus próximos horários e seu histórico.</p></div><button className="btn ghost" onClick={()=>{setLogged(false);setItems([]);setError('')}}>Sair</button></div>{error&&<div className="panel" style={{marginBottom:16}}><b>{error}</b></div>}<div className="client-portal-grid"><div><h2>Próximos horários</h2>{upcoming.length?upcoming.map(card):<div className="panel">Você não tem horários futuros cadastrados.</div>}</div><div><h2>Histórico</h2>{history.length?history.map(card):<div className="panel">Nenhum histórico encontrado.</div>}</div></div>{cancelId&&<div className="client-cancel-backdrop" onClick={()=>setCancelId('')}><div className="client-cancel-modal" onClick={e=>e.stopPropagation()}><h2>Cancelar agendamento</h2><p>Se quiser, informe o motivo do cancelamento.</p><textarea rows="4" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo (opcional)"/><div className="inline"><button className="btn" onClick={cancel} disabled={busy}>{busy?'Cancelando...':'Confirmar cancelamento'}</button><button className="btn ghost" onClick={()=>setCancelId('')}>Voltar</button></div></div></div>}</section>}
