import React,{useEffect,useMemo,useState}from'react';
import{supabase}from'../../lib/supabase';
import{loadRemote}from'../../lib/remote';
import{load}from'../../lib/store';

const toDbStatus={pendente:'pending',confirmado:'confirmed',concluido:'completed',cancelado:'cancelled',nao_compareceu:'no_show'};
const emptyForm={clientName:'',phone:'',serviceId:'',professionalId:'',date:new Date().toISOString().slice(0,10),start:'09:00',duration:120,notes:''};
const localIso=(d,t)=>new Date(`${d}T${t}:00-03:00`).toISOString();
const addMinutes=(d,t,m)=>new Date(new Date(`${d}T${t}:00-03:00`).getTime()+Number(m)*60000).toISOString();
const monthNames=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];

export default function Agenda({data,setData}){
 const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[pro,setPro]=useState('');const[saving,setSaving]=useState('');const[error,setError]=useState('');const[showNew,setShowNew]=useState(false);const[form,setForm]=useState(emptyForm);const[edit,setEdit]=useState(null);const[notice,setNotice]=useState('');
 const activeAppointments=useMemo(()=>data.appointments.filter(a=>a.status!=='cancelado'),[data.appointments]);
 const apps=useMemo(()=>activeAppointments.filter(a=>a.date===date&&(!pro||a.professionalId===pro)).sort((a,b)=>a.start.localeCompare(b.start)),[activeAppointments,date,pro]);
 const selectedYear=Number(date.slice(0,4));
 const monthCounts=useMemo(()=>Array.from({length:12},(_,m)=>activeAppointments.filter(a=>Number(a.date.slice(0,4))===selectedYear&&Number(a.date.slice(5,7))===m+1&&(!pro||a.professionalId===pro)).length),[activeAppointments,selectedYear,pro]);
 async function refresh(){const fresh=await loadRemote(load());setData(fresh)}
 useEffect(()=>{const ch=supabase.channel('agenda-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'appointments'},payload=>{const a=payload.new||{};const dt=String(a.start_datetime||'');const d=dt.slice(0,10).split('-').reverse().join('/');const h=dt?new Date(dt).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'}):'';setNotice(`Nova reserva: ${a.client_name||'cliente'} • ${d}${h?` às ${h}`:''}`);refresh();setTimeout(()=>setNotice(''),8000)}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'appointments'},()=>refresh()).on('postgres_changes',{event:'DELETE',schema:'public',table:'appointments'},()=>refresh()).subscribe();return()=>{supabase.removeChannel(ch)}},[]);
 async function status(id,s){if(s==='cancelado'){const a=data.appointments.find(x=>x.id===id);const ok=window.confirm(`Confirmar cancelamento do horário de ${a?.clientName||'cliente'} em ${a?.date?.split('-').reverse().join('/')} às ${a?.start}?\n\nAo confirmar, o agendamento sairá da agenda e o horário será liberado para outra cliente.`);if(!ok)return;}setSaving(id);setError('');try{const{error}=await supabase.from('appointments').update({status:toDbStatus[s]||s,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;await refresh();if(s==='cancelado')setNotice('Agendamento cancelado. O horário foi liberado novamente.')}catch(e){setError(e.message||'Não foi possível atualizar o status.')}finally{setSaving('')}}
 function chooseService(id){const svc=data.services.find(s=>s.id===id);setForm(f=>({...f,serviceId:id,duration:svc?.duration||f.duration}))}
 async function createManual(e){e.preventDefault();setSaving('new');setError('');try{const svc=data.services.find(s=>s.id===form.serviceId);if(!form.clientName||!form.phone||!form.serviceId||!form.professionalId||!form.date||!form.start)throw new Error('Preencha cliente, WhatsApp, serviço, profissional, data e horário.');const payload={client_name:form.clientName.trim(),client_phone:form.phone.trim(),service_id:form.serviceId,professional_id:form.professionalId,start_datetime:localIso(form.date,form.start),end_datetime:addMinutes(form.date,form.start,form.duration),price:Number(svc?.price||0),status:'confirmed',notes:form.notes||null,source:'admin'};const{error}=await supabase.from('appointments').insert(payload);if(error)throw error;setForm({...emptyForm,date:form.date});setShowNew(false);setDate(form.date);await refresh()}catch(e){setError(e.message?.includes('appointments_no_overlap')?'Este horário conflita com outro agendamento.':e.message||'Não foi possível criar o agendamento.')}finally{setSaving('')}}
 function startEdit(a){const duration=Math.max(1,Math.round((Number(a.end.slice(0,2))*60+Number(a.end.slice(3,5)))-(Number(a.start.slice(0,2))*60+Number(a.start.slice(3,5)))));setEdit({id:a.id,date:a.date,start:a.start,duration})}
 async function saveEdit(){setSaving(edit.id);setError('');try{const{error}=await supabase.from('appointments').update({start_datetime:localIso(edit.date,edit.start),end_datetime:addMinutes(edit.date,edit.start,edit.duration),updated_at:new Date().toISOString()}).eq('id',edit.id);if(error)throw error;setEdit(null);setDate(edit.date);await refresh()}catch(e){setError(e.message?.includes('appointments_no_overlap')?'Não foi possível salvar: o novo horário conflita com outro agendamento.':e.message||'Não foi possível alterar o horário.')}finally{setSaving('')}}
 function selectMonth(m){const mm=String(m+1).padStart(2,'0');const candidates=activeAppointments.filter(a=>a.date.startsWith(`${selectedYear}-${mm}`)&&(!pro||a.professionalId===pro)).sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start));setDate(candidates[0]?.date||`${selectedYear}-${mm}-01`)}
 return <><div className="admin-head"><div><span className="eyebrow">AGENDA</span><h1>Calendário</h1></div><div className="filters"><button className="btn" onClick={()=>setShowNew(v=>!v)}>+ Agendar cliente</button><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><select value={pro} onChange={e=>setPro(e.target.value)}><option value="">Todos profissionais</option>{data.professionals.filter(p=>p.active).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></div></div>
 <div style={{display:'flex',gap:8,overflowX:'auto',padding:'4px 0 14px',marginBottom:8}}>{monthNames.map((name,m)=>{const active=Number(date.slice(5,7))===m+1;const count=monthCounts[m];return <button key={name} type="button" onClick={()=>selectMonth(m)} style={{position:'relative',minWidth:64,padding:'10px 12px',borderRadius:12,border:'1px solid #d8bea1',background:active?'#c98a18':'#fffaf5',fontWeight:700,cursor:'pointer'}}>{name}{count>0&&<span style={{position:'absolute',top:-7,right:-5,minWidth:21,height:21,borderRadius:999,display:'grid',placeItems:'center',padding:'0 5px',fontSize:11,background:'#6b4a2f',color:'white'}}>{count}</span>}</button>})}</div>
 {notice&&<div className="panel" style={{marginBottom:16,borderLeft:'4px solid #c98a18'}}><b>🔔 {notice}</b></div>}{error&&<div className="panel" style={{marginBottom:16}}><b>Erro:</b> {error}</div>}
 {showNew&&<form className="panel form-grid" onSubmit={createManual} style={{marginBottom:18}}><h2 className="span2">Novo agendamento manual</h2><label>Cliente<input value={form.clientName} onChange={e=>setForm({...form,clientName:e.target.value})}/></label><label>WhatsApp<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Serviço<select value={form.serviceId} onChange={e=>chooseService(e.target.value)}><option value="">Selecione</option>{data.services.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Profissional<select value={form.professionalId} onChange={e=>setForm({...form,professionalId:e.target.value})}><option value="">Selecione</option>{data.professionals.filter(p=>p.active&&(!form.serviceId||p.services.includes(form.serviceId))).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Data<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Início<input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Duração real (min)<input type="number" min="10" step="10" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/><small>Você pode usar 120, 150, 180 min etc.</small></label><label>Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="span2"><button className="btn" disabled={saving==='new'}>{saving==='new'?'Salvando...':'Salvar na agenda'}</button></div></form>}
 <div className="calendar-day"><div className="timeline">{Array.from({length:16},(_,i)=><div key={i}>{String(8+i).padStart(2,'0')}:00</div>)}</div><div className="appointments">{apps.length?apps.map(a=>{const svc=data.services.find(s=>s.id===a.serviceId);const p=data.professionals.find(p=>p.id===a.professionalId);return <article className="appointment" key={a.id}><div style={{flex:1}}>{edit?.id===a.id?<div className="form-grid"><label>Data<input type="date" value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value})}/></label><label>Início<input type="time" value={edit.start} onChange={e=>setEdit({...edit,start:e.target.value})}/></label><label>Duração real (min)<input type="number" min="10" step="10" value={edit.duration} onChange={e=>setEdit({...edit,duration:e.target.value})}/></label><div style={{display:'flex',gap:8,alignItems:'end'}}><button className="btn" type="button" onClick={saveEdit} disabled={saving===a.id}>Salvar horário</button><button className="text-button" type="button" onClick={()=>setEdit(null)}>Cancelar</button></div></div>:<><strong>{a.start}–{a.end} • {a.clientName}</strong><span>{svc?.name} • {p?.name}</span><small>{a.phone}</small><button className="text-button" type="button" onClick={()=>startEdit(a)}>Editar horário/duração</button></>}</div><select disabled={saving===a.id} value={a.status} onChange={e=>status(a.id,e.target.value)}><option value="pendente">Pendente</option><option value="confirmado">Confirmado</option><option value="concluido">Concluído</option><option value="cancelado">Cancelar agendamento</option><option value="nao_compareceu">Não compareceu</option></select></article>}):<div className="empty">Nenhum agendamento neste dia.</div>}</div></div></>;
}
