import{useEffect,useState}from'react';
import{supabase}from'../../lib/supabase';

const V={cliente:'{{cliente}}',data:'{{data}}',hora:'{{hora}}',servico:'{{servico}}',profissional:'{{profissional}}'};
const defaults={admin_phone:'',enabled:false,provider:'meta_cloud_api',confirmation_template:`Olá ${V.cliente}! Seu horário no Studio Nayumi Siqueira foi reservado para ${V.data} às ${V.hora}. Serviço: ${V.servico} com ${V.profissional}.`,reminder_template:`Olá ${V.cliente}! Passando para lembrar que você tem horário amanhã, ${V.data}, às ${V.hora}, no Studio Nayumi Siqueira. Serviço: ${V.servico}.`,cancellation_template:`Olá ${V.cliente}! Seu agendamento de ${V.data} às ${V.hora} foi cancelado. Se quiser, você pode escolher um novo horário pelo nosso site.`,admin_new_booking_template:`Nova reserva: ${V.cliente} • ${V.servico} • ${V.data} às ${V.hora} • ${V.profissional}.`,admin_cancel_template:`Cancelamento: ${V.cliente} • ${V.servico} • ${V.data} às ${V.hora} • ${V.profissional}.`};

export default function Integrations(){const[wa,setWa]=useState(defaults);const[id,setId]=useState(null);const[saving,setSaving]=useState(false);const[msg,setMsg]=useState('');
useEffect(()=>{(async()=>{const{data,error}=await supabase.from('whatsapp_settings').select('*').limit(1).maybeSingle();if(!error&&data){setId(data.id);setWa({...defaults,...data})}})()},[]);
async function save(){setSaving(true);setMsg('');try{const payload={admin_phone:wa.admin_phone,enabled:wa.enabled,provider:wa.provider,confirmation_template:wa.confirmation_template,reminder_template:wa.reminder_template,cancellation_template:wa.cancellation_template,admin_new_booking_template:wa.admin_new_booking_template,admin_cancel_template:wa.admin_cancel_template,updated_at:new Date().toISOString()};let q=id?await supabase.from('whatsapp_settings').update(payload).eq('id',id).select().single():await supabase.from('whatsapp_settings').insert(payload).select().single();if(q.error)throw q.error;if(q.data?.id)setId(q.data.id);setMsg('Configurações salvas.');}catch(e){setMsg(e.message||'Erro ao salvar.')}finally{setSaving(false)}}
return <><div className="admin-head"><h1>Integrações</h1></div><div className="cards"><article className="card span2"><div className="row"><h3>WhatsApp</h3><span className={`badge ${wa.enabled?'':'off'}`}>{wa.enabled?'Configurado':'Aguardando conexão da API'}</span></div><p>Cadastre seu número e personalize as mensagens automáticas. Para o envio automático funcionar de verdade, ainda é necessário conectar uma conta oficial do WhatsApp Business pela Meta Cloud API ou outro provedor autorizado.</p><div className="form-grid"><label className="span2">Seu número do WhatsApp<input placeholder="Ex.: 5551999999999" value={wa.admin_phone||''} onChange={e=>setWa({...wa,admin_phone:e.target.value.replace(/\D/g,'')})}/><small>Use DDI + DDD + número, somente números.</small></label><label className="span2">Mensagem para a cliente ao confirmar reserva<textarea rows="4" value={wa.confirmation_template||''} onChange={e=>setWa({...wa,confirmation_template:e.target.value})}/></label><label className="span2">Lembrete 1 dia antes<textarea rows="4" value={wa.reminder_template||''} onChange={e=>setWa({...wa,reminder_template:e.target.value})}/></label><label className="span2">Mensagem de cancelamento para a cliente<textarea rows="4" value={wa.cancellation_template||''} onChange={e=>setWa({...wa,cancellation_template:e.target.value})}/></label><label className="span2">Aviso para você quando entrar nova reserva<textarea rows="4" value={wa.admin_new_booking_template||''} onChange={e=>setWa({...wa,admin_new_booking_template:e.target.value})}/></label><label className="span2">Aviso para você quando houver cancelamento<textarea rows="4" value={wa.admin_cancel_template||''} onChange={e=>setWa({...wa,admin_cancel_template:e.target.value})}/></label></div><p className="hint">Você pode usar: {'{{cliente}}'}, {'{{data}}'}, {'{{hora}}'}, {'{{servico}}'} e {'{{profissional}}'}.</p><div className="inline"><button className="btn" onClick={save} disabled={saving}>{saving?'Salvando...':'Salvar WhatsApp'}</button>{wa.admin_phone&&<button className="btn ghost" onClick={()=>window.open(`https://wa.me/${wa.admin_phone}`,'_blank')}>Testar número</button>}</div>{msg&&<p><b>{msg}</b></p>}</article><article className="card"><div className="row"><h3>Automação</h3><span className="badge off">API pendente</span></div><p>Fluxo preparado para: aviso de nova reserva para você, confirmação para a cliente, lembrete 24h antes e avisos de cancelamento.</p><p className="hint">O número sozinho não permite disparos automáticos pelo WhatsApp. A Meta exige uma conexão oficial e, em muitos casos, modelos de mensagem aprovados.</p></article><article className="card"><div className="row"><h3>MinhaAgenda</h3><span className="badge off">Não conectado</span></div><p>Estrutura preparada para sincronização futura de serviços, profissionais, horários e compromissos.</p><button className="btn ghost" disabled>Conectar quando houver API</button></article></div></>}
